/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClaudePromptRouteImport } from './routes/claude-prompt'
import { Route as IndexRouteImport } from './routes/index'

const ClaudePromptRoute = ClaudePromptRouteImport.update({
  id: '/claude-prompt',
  path: '/claude-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claude-prompt': typeof ClaudePromptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claude-prompt': typeof ClaudePromptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claude-prompt': typeof ClaudePromptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/claude-prompt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/claude-prompt'
  id: '__root__' | '/' | '/claude-prompt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaudePromptRoute: typeof ClaudePromptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/claude-prompt': {
      id: '/claude-prompt'
      path: '/claude-prompt'
      fullPath: '/claude-prompt'
      preLoaderRoute: typeof ClaudePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaudePromptRoute: ClaudePromptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
